apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    foo: changed
spec:
  selector:
    app.kubernetes.io/name: proxy
  externalName: nginx
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http-web-svc
