# This deployment is meant to represent the bug at https://github.com/rancher/fleet/issues/2521
# It includes:
# - A spec field "paused" set to its default value
# - A non-empty "status", despite being a subresource and not modifiable by apply
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drift-dummy-deployment
  labels:
    app: drift-dummy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drift-dummy
  template:
    metadata:
      labels:
        app: drift-dummy
    spec:
      containers:
      - name: pause
        image: k8s.gcr.io/pause
        ports:
        - containerPort: 80
  paused: false
status:
  collisionCount: 0
